[package]
name = "word_filtering"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.0"
once_cell = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0" # For testing
clap = { version = "4.0", features = ["derive"] }