package com.backend.restservice.controllers;
import com.backend.restservice.models.*;
import com.backend.restservice.repositories.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class TeacherController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StateRepository stateRepository;

    @Autowired
    JdbcTemplate database;

    @GetMapping(path="/state/all")
    public @ResponseBody Iterable<State> getAllUsers() {
        // This returns a JSON or XML with the users
        int rowCount = this.database.
                queryForObject("select count(*) from state", Integer.class);
        System.out.println("\n*****count:" + rowCount);
        return stateRepository.findAll();
    }
}